name: CI
 
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'app/**'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'app/**'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
 
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
 
      - name: Install dependencies
        run: npm install
 
      - name: Run prettier
        run: npm run prettier:check-library
 
      - name: Run lint
        run: npm run lint:library
 
  release:
    needs: build
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
 
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
 
      - name: Install dependencies
        run: npm install
 
      - name: Semantic Release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
        run: npm run semantic-release